#+title: indent-lint.el
#+author: Naoya Yamashita

[[https://github.com/conao3/indent-lint.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/indent-lint.el.svg?style=flat-square]]
[[https://github.com/conao3/indent-lint.el/releases][https://img.shields.io/github/tag/conao3/indent-lint.el.svg?style=flat-square]]
[[https://github.com/conao3/indent-lint.el/actions][https://github.com/conao3/indent-lint.el/workflows/Main%20workflow/badge.svg]]

Asynchronous indentation linter for Emacs with Flycheck integration.

* Overview

indent-lint.el checks your buffer's indentation against Emacs's built-in indentation rules by running the comparison in a clean, isolated Emacs subprocess. This approach ensures accurate results without interference from your current configuration state.

The package includes =flycheck-indent=, a Flycheck checker that provides real-time indentation feedback as you write code.

* Installation

Both packages are available on MELPA:

#+begin_src emacs-lisp
  (package-install 'indent-lint)
  (package-install 'flycheck-indent)
#+end_src

Or with =use-package=:

#+begin_src emacs-lisp
  (use-package indent-lint)

  (use-package flycheck-indent
    :after flycheck
    :config
    (flycheck-indent-setup))
#+end_src

* Usage

** Interactive Use

Run =M-x indent-lint= to check the current buffer. After a moment, a diff buffer will appear showing any lines with incorrect indentation.

** Programmatic Use

#+begin_src emacs-lisp
  (indent-lint BUFFER)
#+end_src

=BUFFER= accepts either a buffer name (string) or buffer object.

** Flycheck Integration

Enable the Flycheck checker with:

#+begin_src emacs-lisp
  (with-eval-after-load 'flycheck
    (flycheck-indent-setup))
#+end_src

This chains the indent checker after the standard Emacs Lisp checkers.

** Batch Mode

For CI pipelines or pre-commit hooks:

#+begin_src shell
  emacs -Q --batch -l indent-lint.el -f indent-lint-batch file1.el file2.el
#+end_src

Exit codes:
- 0: No indentation errors
- 1: Indentation errors found
- 2: Diff program error
- 3: Error during indentation processing
- 100: Timeout

* Configuration

| Variable                      | Description                                      | Default   |
|-------------------------------+--------------------------------------------------+-----------|
| =indent-lint-before-indent-fn=  | Function to run before indenting (receives buffers) | =#'ignore=  |
| =indent-lint-verbose=           | Show full diff output                            | =t=         |
| =indent-lint-popup=             | Automatically display diff buffer                | =t=         |
| =indent-lint-batch-timeout=     | Timeout for batch operations (seconds)           | =10=        |

* Requirements

- Emacs 27.1 or later
- [[https://github.com/chuntaro/emacs-async-await][async-await]]
- [[https://github.com/jwiegley/emacs-async][async]]
- [[https://github.com/chuntaro/emacs-promise][promise]]
- [[https://www.flycheck.org/][flycheck]] (for flycheck-indent)

* Contributing

Contributions are welcome. Please open an issue or submit a pull request on GitHub.

To run the test suite locally:

#+begin_src shell
  # Install Cask (https://github.com/cask/cask)
  make test
#+end_src

* License

GPL-3.0. See [[https://github.com/conao3/indent-lint.el/blob/master/LICENSE][LICENSE]] for details.

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
